# Generated by Django 6.0.4 on 2026-04-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.IntegerField(default=1),
        ),
    ]
