# Generated by Django 6.0.4 on 2026-04-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_remove_tarea_prioridad_tarea_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='completada',
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
